language: node_js
deploy:
  provider: npm
  email: scjosh2@gmail.com
  api_key:
    secure: "RXFp71w3SseF+Xx8K0+VyEhQijR00tVMQKfto2J9Zxl34ZnD1JaaycCJq+ZMC6YHqG3ZBEjbFANLXTcMubBxr0i3WZ/jGdcdimbBTXmJq8J/ADZWJtlfBLi6jRSCdTC0LyS1UsALGsU0qP6eTF8kd1ewohvJghSAfPE05MaTaK4="
  on:
    repo: joshuaferrara/node-csgo
node_js:
    - 'node'
sudo: false
